[project]
name = "python-binding-profiling"
version = "0.1.0"
description = "This repo profiles a number of C and CPP python extensions determining which is the best for different use cases"

readme = "README.md"

requires-python = ">=3.12,<3.13"

dependencies = [
    "numpy>=1.24.4",
    "pure-python-package",
    "numba-package",
    "matplotlib>=3.10.8",
    "cython-package",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.uv.sources]
pure-python-package = { path = "python/pure_python/dist/pure_python_package-0.1.0-py3-none-any.whl" }
numba-package = {path = "python/numba_package/dist/numba_package-0.1.0-py3-none-any.whl"}
cython-package = { path = "python/cython_package/dist/cython_package-0.1.0-cp312-cp312-macosx_14_0_arm64.whl" }

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["src/python_binding_profiling"]
