[project]
name = "cython-package"
version = "0.1.0"
description = "This a toy package for profiling function"
requires-python = ">=3.12,<3.13"

dependencies = [
    "setuptools>=64",
    "numpy>=1.24.4",
    "Cython>=3.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=64",
    "numpy>=1.24.4",
    "Cython>=3.0",
]

[tool.uv]
package = true
